# Generated by Django 3.2.20 on 2023-08-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0008_auto_20230820_1923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
